name: hourly-taxi-demand-feature-pipeline

on:
  schedule:
  - cron: '0 * * * *'

jobs:

  feature_pipeline:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Python 3.11.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    
    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
        
    - name: execute python workflows from bash scripts
      env: 
        HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb
  
